// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxkkc3ghF5_SVxsmp48I_4Mtz1NoZF5U',
    appId: '1:281864671890:web:892ccc074b719361b30c4b',
    messagingSenderId: '281864671890',
    projectId: 'crudapp-951c6',
    authDomain: 'crudapp-951c6.firebaseapp.com',
    storageBucket: 'crudapp-951c6.appspot.com',
    measurementId: 'G-0THR1CLPM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5h9_68zmvBmLy_itr6o52fyGd8QwLLB8',
    appId: '1:281864671890:android:a26f20b62dfcb474b30c4b',
    messagingSenderId: '281864671890',
    projectId: 'crudapp-951c6',
    storageBucket: 'crudapp-951c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIt_keRx5wMRbTp2P5XVp_cyrmIWrJE8',
    appId: '1:281864671890:ios:92db723eda0e01c0b30c4b',
    messagingSenderId: '281864671890',
    projectId: 'crudapp-951c6',
    storageBucket: 'crudapp-951c6.appspot.com',
    iosBundleId: 'com.example.bucket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIt_keRx5wMRbTp2P5XVp_cyrmIWrJE8',
    appId: '1:281864671890:ios:cb15ae37d475a0c2b30c4b',
    messagingSenderId: '281864671890',
    projectId: 'crudapp-951c6',
    storageBucket: 'crudapp-951c6.appspot.com',
    iosBundleId: 'com.example.bucket.RunnerTests',
  );
}
